### ISSUE TITLE
Breaking changes to `watch` API in esbuild `v0.17.0`

### ISSUE THREAD

**Issue by hawkticehurst** [connor4312/esbuild-problem-matchers#3]
Esbuild recently [released breaking changes in `v0.17.0`](https://github.com/evanw/esbuild/releases/tag/v0.17.0), especially with regards to its incremental, watch, and serve APIs.

The `onRebuild` has specifically been removed (and replaced with an `onEnd` callback) and the [example code snippet](https://github.com/connor4312/esbuild-problem-matchers#esbuild-via-js) in the README of this repo will no longer run when v0.17+ is installed.

Request: Update the sample code snippet in the README and potentially update the problem matcher config if needed (truthfully I'm unfamiliar with how problem matchers work).

Thanks!

**Comment by relative** [comment]
this should work on esbuild v0.17.x (tested on v0.17.10)
```js
/**
 * @type {import('esbuild').Plugin}
 */
const esbuildProblemMatcherPlugin = {
  name: 'esbuild-problem-matcher',

  setup(build) {
    build.onStart(() => {
      console.log('[watch] build started')
    })
    build.onEnd(result => {
      if (result.errors.length) {
        result.errors.forEach(error =>
          console.error(
            `> ${error.location.file}:${error.location.line}:${error.location.column}: error: ${error.text}`
          )
        )
      } else console.log('[watch] build finished')
    })
  },
}

// add the esbuildProblemMatcherPlugin to the esbuild plugins array
await esbuild.context({
  /* ... your options */
  plugins: [
    /* add to the end of plugins array */
    esbuildProblemMatcherPlugin
  ]
})
```

**Comment by shd101wyy** [comment]
Thank you so much @relative ! :+1: You saved my day!

**Comment by connor4312** [comment]
Thanks, updated :)

**Comment by maninak** [comment]
The problem matcher doesn't seem to work for me with the above-suggested solution :/

```js
// esbuild.js

const { build } = require('esbuild')

/**
 * @type {import('esbuild').Plugin}
 */
const esbuildProblemMatcherPlugin = {
  name: 'esbuild-problem-matcher',

  setup(build) {
    build.onStart(() => {
      console.log('[watch] build started')
    })
    build.onEnd((result) => {
      result.errors.forEach(({ text }) => {
        console.error(`✘ [ERROR] ${text}`)
        // @ts-expect-error Property does not exist on type 'Location'.
        console.error(`    ${location.file}:${location.line}:${location.column}`)
      })
      console.log('[watch] build finished')
    })
  },
}

/** @type {import('esbuild').BuildOptions} */
const baseConfig = {
  bundle: true,
  minify: process.env.NODE_ENV === 'production',
  sourcemap: process.env.NODE_ENV !== 'production',
  plugins: process.env.NODE_ENV === 'production' ? [] : [esbuildProblemMatcherPlugin],
}

/** @type {import('esbuild').BuildOptions} */
const extensionConfig = {
  ...baseConfig,
  platform: 'node',
  target: 'es2020',
  mainFields: ['module', 'main'],
  format: 'cjs',
  entryPoints: ['./src/extension.ts'],
  outfile: './dist/extension.js',
  external: ['vscode'],
}

/** @type {import('esbuild').BuildOptions} */
const webviewConfig = {
  ...baseConfig,
  target: 'es2020',
  format: 'esm',
  entryPoints: ['./src/webview/main.ts'],
  outfile: './dist/webview.js',
}

;(async () => {
  try {
    await build(extensionConfig)
    await build(webviewConfig)
    console.log('build complete')
  } catch (err) {
    process.stderr.write(err.stderr)
    process.exit(1)
  }
})()
```

Output is

```
> radicle@0.3.2 compile
> node ./esbuild.js --watch

[watch] build started
[watch] build finished
[watch] build started
[watch] build finished
build complete
 *  Terminal will be reused by tasks, press any key to close it. 
 ```

![image](https://github.com/connor4312/esbuild-problem-matchers/assets/7542054/1688eea4-6b4b-4f2b-9087-d5163f254c44)


Note the last line, which is the issue.

Using esbuild v0.19.9

**Comment by connor4312** [comment]
@maninak if you're manually emitting output in that format, you'll want to use the `esbuild-0.13` / `esbuild-0.13-watch` problem matcher since that's the pre-0.14 esbuild format.

**Comment by maninak** [comment]
@connor4312 thank you for offering your help!

Unfortunately using esbuild-0.13-watch didn't have any effect. Please note that in my previous comment, I'm stating that I'm using esbuild v0.19.9 .

The emitting output format is the result of following the [latest readme](https://github.com/connor4312/esbuild-problem-matchers/blob/3d6981c1155c3cc01e431bbfe627c2036fb247ce/README.md) :man_shrugging: 

Here's my `tasks.json` (with your suggested changes)

```jsonc
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "dev",
      "detail": "Launch extension for local development in a new (host) VS Code window.",
      "problemMatcher": "$esbuild-0.13-watch",
      "isBackground": true,
      "presentation": { "reveal": "silent" },
      "group": {
        "kind": "build",
        "isDefault": true,
      },
      "icon": { "id": "tools" },
    },
    /**
     * HACK:
     *
     * Ideally we'd terminate a specific task e.g. `npm: dev`,
     * but this seems not feasible as of writing this (not without the user needing
     * to manually select which running task to close).
     * @see https://stackoverflow.com/questions/54480792/terminate-another-task-from-within-a-postdebugtask-vs-code
     */
    {
      "label": "Terminate All Tasks",
      "detail": "Stop all running tasks.", // e.g. useful for endless tasks like file watchers
      "command": "echo ${input:terminate}",
      "type": "shell",
      "problemMatcher": [],
      "icon": { "id": "stop-circle" },
    },
  ],
  "inputs": [
    {
      "id": "terminate",
      "type": "command",
      "command": "workbench.action.tasks.terminate",
      "args": "terminateAll",
    },
  ],
}

```

**Comment by connor4312** [comment]
You may be hitting this issue https://github.com/microsoft/vscode/issues/194501

> Please note that in my previous comment, I'm stating that I'm using esbuild v0.19.9 .

Yes, however, the `[watch] build <...>` is the format that esbuild emitted before 0.14, so by manually emitting that yourself, you need to use the 0.13 matchers
